env: "local"
databaseHost: "db"
databasePort: 5432
databaseUser: "postgres"
databaseName: "oggetto"
databasePassword: "lolkek123"
databaseSSLMode: "disable"
secretKey: "django-insecure-d=a2pod6zatg32i@lh0gmhcjjo1wr71$&c@6hl-co3%nqpgs$)"