definitions:
  handlers.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  handlers.LeaderBoardStatistics:
    properties:
      fio:
        type: string
      place:
        type: integer
      score:
        type: integer
    type: object
  handlers.ProfileResponseStatisticsDoc:
    properties:
      date:
        example: "2024-10-26T00:00:00Z"
        type: string
      in_progress_count:
        example: 3
        type: integer
      success_count:
        example: 5
        type: integer
    type: object
info:
  contact: {}
paths:
  /get-leaderboard/{period}/{count}:
    get:
      description: Возвращает список топ-N самых активных участников за последние
        X дней, отсортированный по количеству завершенных задач.
      parameters:
      - description: Период в днях для определения активности (например, 7 для последней
          недели)
        in: path
        name: period
        required: true
        type: integer
      - description: Количество записей в списке топа (например, 10 для топ-10)
        in: path
        name: count
        required: true
        type: integer
      responses:
        "200":
          description: Список участников с их местом, ФИО и количеством завершенных
            задач
          schema:
            items:
              $ref: '#/definitions/handlers.LeaderBoardStatistics'
            type: array
        "400":
          description: Описание ошибки в случае некорректного запроса
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить топ активных участников за указанный период
      tags:
      - statistics
  /getStatistic/user/{user_id}:
    get:
      description: 'Возвращает статистику задач для пользователя: завершенные и находящиеся
        в процессе задачи для каждой даты'
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.ProfileResponseStatisticsDoc'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить статистику пользователя по его ID
      tags:
      - statistics
swagger: "2.0"
